---
- name: provision a tox/molecule/ansible host
  hosts: all
  roles:
    - role: openstack.redhat-subscription
      become: true

  tasks:

    - name: put selinux into permissive mode so PY3 works
      selinux:
        policy: targeted
        state: disabled
      register: selinux
      become: true

    - name: create a docker group
      group:
        name: docker
      become: true

    - name: add {{ ansible_user }} to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
      become: true

    - name: install python scl packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - tmux
          - vim
          - docker
          - python-devel.x86_64
          - python-docker-py.noarch
          - rh-python36
          - rh-python36-python-devel.x86_64
          - gcc
          - git
      become: true

    - name: start docker
      service:
        name: docker
        state: started
        enabled: true
      become: true

    - name: install tox
      pip:
        name: tox
        umask: "0022"
      environment:
        PATH: /opt/rh/rh-python36/root/usr/bin
        LD_LIBRARY_PATH: /opt/rh/rh-python36/root/usr/lib64
      become: true

    - name: set ec2 region
      lineinfile:
        path: ~/.bash_profile
        regexp: "^export AWS_REGION="
        line: "export AWS_REGION=eu-west-1"

    - name: create aws config folder
      file:
        path: ~/.aws
        state: directory
        mode: 0755

    - name: lookup aws credentials
      set_fact:
        aws_access_key_id : "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_access_key : "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      no_log: true

    - name: copy aws credentials
      copy:
        content: "[default]\naws_access_key_id = {{ aws_access_key_id }}\naws_secret_access_key = {{ aws_secret_access_key }}\n"
        dest: ~/.aws/credentials
        mode: 0600

    - name: copy aws config
      copy:
        content: |
                [default]
                region = eu-west-1
        dest: ~/.aws/config
        mode: 0600

