---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-0e12cbde3e77cbb98
    instance_type: t2.micro
    vpc_subnet_id: subnet-83addbcb
    region: eu-west-1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python
  config_options:
    ssh_connection:
      control_path:
scenario:
  name: ec2
verifier:
  name: testinfra
  lint:
    name: flake8
