---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-3548444c
    instance_type: t2.micro
    vpc_subnet_id: subnet-83addbcb
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ec2
verifier:
  name: testinfra
  lint:
    name: flake8
