---
# handlers file for lshake.caddy

- name: systemd daemon reload
  systemd:
    name: "{{ caddy_service_name }}"
    daemon_reload: true

- name: restart caddy
  service:
    name: "{{ caddy_service_name }}"
    state: restarted
